package webhook

import "time"

// github的Push返回的所有Json
type GithubPushHook struct {
	Ref        string `json:"ref"`
	Before     string `json:"before"`
	After      string `json:"after"`
	Repository struct {
		Id       int    `json:"id"`
		NodeId   string `json:"node_id"`
		Name     string `json:"name"`
		FullName string `json:"full_name"`
		Private  bool   `json:"private"`
		Owner    struct {
			Name              string `json:"name"`
			Email             string `json:"email"`
			Login             string `json:"login"`
			Id                int    `json:"id"`
			NodeId            string `json:"node_id"`
			AvatarUrl         string `json:"avatar_url"`
			GravatarId        string `json:"gravatar_id"`
			Url               string `json:"url"`
			HtmlUrl           string `json:"html_url"`
			FollowersUrl      string `json:"followers_url"`
			FollowingUrl      string `json:"following_url"`
			GistsUrl          string `json:"gists_url"`
			StarredUrl        string `json:"starred_url"`
			SubscriptionsUrl  string `json:"subscriptions_url"`
			OrganizationsUrl  string `json:"organizations_url"`
			ReposUrl          string `json:"repos_url"`
			EventsUrl         string `json:"events_url"`
			ReceivedEventsUrl string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"owner"`
		HtmlUrl          string      `json:"html_url"`
		Description      string      `json:"description"`
		Fork             bool        `json:"fork"`
		Url              string      `json:"url"`
		ForksUrl         string      `json:"forks_url"`
		KeysUrl          string      `json:"keys_url"`
		CollaboratorsUrl string      `json:"collaborators_url"`
		TeamsUrl         string      `json:"teams_url"`
		HooksUrl         string      `json:"hooks_url"`
		IssueEventsUrl   string      `json:"issue_events_url"`
		EventsUrl        string      `json:"events_url"`
		AssigneesUrl     string      `json:"assignees_url"`
		BranchesUrl      string      `json:"branches_url"`
		TagsUrl          string      `json:"tags_url"`
		BlobsUrl         string      `json:"blobs_url"`
		GitTagsUrl       string      `json:"git_tags_url"`
		GitRefsUrl       string      `json:"git_refs_url"`
		TreesUrl         string      `json:"trees_url"`
		StatusesUrl      string      `json:"statuses_url"`
		LanguagesUrl     string      `json:"languages_url"`
		StargazersUrl    string      `json:"stargazers_url"`
		ContributorsUrl  string      `json:"contributors_url"`
		SubscribersUrl   string      `json:"subscribers_url"`
		SubscriptionUrl  string      `json:"subscription_url"`
		CommitsUrl       string      `json:"commits_url"`
		GitCommitsUrl    string      `json:"git_commits_url"`
		CommentsUrl      string      `json:"comments_url"`
		IssueCommentUrl  string      `json:"issue_comment_url"`
		ContentsUrl      string      `json:"contents_url"`
		CompareUrl       string      `json:"compare_url"`
		MergesUrl        string      `json:"merges_url"`
		ArchiveUrl       string      `json:"archive_url"`
		DownloadsUrl     string      `json:"downloads_url"`
		IssuesUrl        string      `json:"issues_url"`
		PullsUrl         string      `json:"pulls_url"`
		MilestonesUrl    string      `json:"milestones_url"`
		NotificationsUrl string      `json:"notifications_url"`
		LabelsUrl        string      `json:"labels_url"`
		ReleasesUrl      string      `json:"releases_url"`
		DeploymentsUrl   string      `json:"deployments_url"`
		CreatedAt        int64       `json:"created_at"`
		UpdatedAt        time.Time   `json:"updated_at"`
		PushedAt         int         `json:"pushed_at"`
		GitUrl           string      `json:"git_url"`
		SshUrl           string      `json:"ssh_url"`
		CloneUrl         string      `json:"clone_url"`
		SvnUrl           string      `json:"svn_url"`
		Homepage         interface{} `json:"homepage"`
		Size             int         `json:"size"`
		StargazersCount  int         `json:"stargazers_count"`
		WatchersCount    int         `json:"watchers_count"`
		Language         string      `json:"language"`
		HasIssues        bool        `json:"has_issues"`
		HasProjects      bool        `json:"has_projects"`
		HasDownloads     bool        `json:"has_downloads"`
		HasWiki          bool        `json:"has_wiki"`
		HasPages         bool        `json:"has_pages"`
		ForksCount       int         `json:"forks_count"`
		MirrorUrl        interface{} `json:"mirror_url"`
		Archived         bool        `json:"archived"`
		Disabled         bool        `json:"disabled"`
		OpenIssuesCount  int         `json:"open_issues_count"`
		License          interface{} `json:"license"`
		Forks            int         `json:"forks"`
		OpenIssues       int         `json:"open_issues"`
		Watchers         int         `json:"watchers"`
		DefaultBranch    string      `json:"default_branch"`
		Stargazers       int         `json:"stargazers"`
		MasterBranch     string      `json:"master_branch"`
	} `json:"repository"`
	Pusher struct {
		Name  string `json:"name"`
		Email string `json:"email"`
	} `json:"pusher"`
	Sender struct {
		Login             string `json:"login"`
		Id                int    `json:"id"`
		NodeId            string `json:"node_id"`
		AvatarUrl         string `json:"avatar_url"`
		GravatarId        string `json:"gravatar_id"`
		Url               string `json:"url"`
		HtmlUrl           string `json:"html_url"`
		FollowersUrl      string `json:"followers_url"`
		FollowingUrl      string `json:"following_url"`
		GistsUrl          string `json:"gists_url"`
		StarredUrl        string `json:"starred_url"`
		SubscriptionsUrl  string `json:"subscriptions_url"`
		OrganizationsUrl  string `json:"organizations_url"`
		ReposUrl          string `json:"repos_url"`
		EventsUrl         string `json:"events_url"`
		ReceivedEventsUrl string `json:"received_events_url"`
		Type              string `json:"type"`
		SiteAdmin         bool   `json:"site_admin"`
	} `json:"sender"`
	Created bool        `json:"created"`
	Deleted bool        `json:"deleted"`
	Forced  bool        `json:"forced"`
	BaseRef interface{} `json:"base_ref"`
	Compare string      `json:"compare"`
	Commits []struct {
		Id        string    `json:"id"`
		TreeId    string    `json:"tree_id"`
		Distinct  bool      `json:"distinct"`
		Message   string    `json:"message"`
		Timestamp time.Time `json:"timestamp"`
		Url       string    `json:"url"`
		Author    struct {
			Name     string `json:"name"`
			Email    string `json:"email"`
			Username string `json:"username"`
		} `json:"author"`
		Committer struct {
			Name     string `json:"name"`
			Email    string `json:"email"`
			Username string `json:"username"`
		} `json:"committer"`
		Added    []interface{} `json:"added"`
		Removed  []interface{} `json:"removed"`
		Modified []string      `json:"modified"`
	} `json:"commits"`
	HeadCommit struct {
		Id        string    `json:"id"`
		TreeId    string    `json:"tree_id"`
		Distinct  bool      `json:"distinct"`
		Message   string    `json:"message"`
		Timestamp time.Time `json:"timestamp"`
		Url       string    `json:"url"`
		Author    struct {
			Name     string `json:"name"`
			Email    string `json:"email"`
			Username string `json:"username"`
		} `json:"author"`
		Committer struct {
			Name     string `json:"name"`
			Email    string `json:"email"`
			Username string `json:"username"`
		} `json:"committer"`
		Added    []interface{} `json:"added"`
		Removed  []interface{} `json:"removed"`
		Modified []string      `json:"modified"`
	} `json:"head_commit"`
}

// github的PullRequest返回的所有Json
type GithubPRHook struct {
	Action      string `json:"action"`
	Number      int64  `json:"number"`
	PullRequest struct {
		Url      string `json:"url"`
		Id       int    `json:"id"`
		NodeId   string `json:"node_id"`
		HtmlUrl  string `json:"html_url"`
		DiffUrl  string `json:"diff_url"`
		PatchUrl string `json:"patch_url"`
		IssueUrl string `json:"issue_url"`
		Number   int    `json:"number"`
		State    string `json:"state"`
		Locked   bool   `json:"locked"`
		Title    string `json:"title"`
		User     struct {
			Login             string `json:"login"`
			Id                int    `json:"id"`
			NodeId            string `json:"node_id"`
			AvatarUrl         string `json:"avatar_url"`
			GravatarId        string `json:"gravatar_id"`
			Url               string `json:"url"`
			HtmlUrl           string `json:"html_url"`
			FollowersUrl      string `json:"followers_url"`
			FollowingUrl      string `json:"following_url"`
			GistsUrl          string `json:"gists_url"`
			StarredUrl        string `json:"starred_url"`
			SubscriptionsUrl  string `json:"subscriptions_url"`
			OrganizationsUrl  string `json:"organizations_url"`
			ReposUrl          string `json:"repos_url"`
			EventsUrl         string `json:"events_url"`
			ReceivedEventsUrl string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"user"`
		Body               string        `json:"body"`
		CreatedAt          time.Time     `json:"created_at"`
		UpdatedAt          time.Time     `json:"updated_at"`
		ClosedAt           interface{}   `json:"closed_at"`
		MergedAt           interface{}   `json:"merged_at"`
		MergeCommitSha     interface{}   `json:"merge_commit_sha"`
		Assignee           interface{}   `json:"assignee"`
		Assignees          []interface{} `json:"assignees"`
		RequestedReviewers []interface{} `json:"requested_reviewers"`
		RequestedTeams     []interface{} `json:"requested_teams"`
		Labels             []interface{} `json:"labels"`
		Milestone          interface{}   `json:"milestone"`
		Draft              bool          `json:"draft"`
		CommitsUrl         string        `json:"commits_url"`
		ReviewCommentsUrl  string        `json:"review_comments_url"`
		ReviewCommentUrl   string        `json:"review_comment_url"`
		CommentsUrl        string        `json:"comments_url"`
		StatusesUrl        string        `json:"statuses_url"`
		Head               struct {
			Label string `json:"label"`
			Ref   string `json:"ref"`
			Sha   string `json:"sha"`
			User  struct {
				Login             string `json:"login"`
				Id                int    `json:"id"`
				NodeId            string `json:"node_id"`
				AvatarUrl         string `json:"avatar_url"`
				GravatarId        string `json:"gravatar_id"`
				Url               string `json:"url"`
				HtmlUrl           string `json:"html_url"`
				FollowersUrl      string `json:"followers_url"`
				FollowingUrl      string `json:"following_url"`
				GistsUrl          string `json:"gists_url"`
				StarredUrl        string `json:"starred_url"`
				SubscriptionsUrl  string `json:"subscriptions_url"`
				OrganizationsUrl  string `json:"organizations_url"`
				ReposUrl          string `json:"repos_url"`
				EventsUrl         string `json:"events_url"`
				ReceivedEventsUrl string `json:"received_events_url"`
				Type              string `json:"type"`
				SiteAdmin         bool   `json:"site_admin"`
			} `json:"user"`
			// 早期的 GitHub API 版本中，使用的是 repo 关键字来表示代码仓库。而在后来的版本中，GitHub 将其改为了 repository。这样做是为了更好地统一 API 的命名风格，并提供更清晰、更一致的接口
			// 可以将 repository 和 repo 视为同义词，它们都表示 GitHub 代码仓库的信息，只是在不同版本的 API 中使用不同的关键字来表示
			Repo struct {
				Id       int    `json:"id"`
				NodeId   string `json:"node_id"`
				Name     string `json:"name"`
				FullName string `json:"full_name"`
				Private  bool   `json:"private"`
				Owner    struct {
					Login             string `json:"login"`
					Id                int    `json:"id"`
					NodeId            string `json:"node_id"`
					AvatarUrl         string `json:"avatar_url"`
					GravatarId        string `json:"gravatar_id"`
					Url               string `json:"url"`
					HtmlUrl           string `json:"html_url"`
					FollowersUrl      string `json:"followers_url"`
					FollowingUrl      string `json:"following_url"`
					GistsUrl          string `json:"gists_url"`
					StarredUrl        string `json:"starred_url"`
					SubscriptionsUrl  string `json:"subscriptions_url"`
					OrganizationsUrl  string `json:"organizations_url"`
					ReposUrl          string `json:"repos_url"`
					EventsUrl         string `json:"events_url"`
					ReceivedEventsUrl string `json:"received_events_url"`
					Type              string `json:"type"`
					SiteAdmin         bool   `json:"site_admin"`
				} `json:"owner"`
				HtmlUrl             string      `json:"html_url"`
				Description         string      `json:"description"`
				Fork                bool        `json:"fork"`
				Url                 string      `json:"url"`
				ForksUrl            string      `json:"forks_url"`
				KeysUrl             string      `json:"keys_url"`
				CollaboratorsUrl    string      `json:"collaborators_url"`
				TeamsUrl            string      `json:"teams_url"`
				HooksUrl            string      `json:"hooks_url"`
				IssueEventsUrl      string      `json:"issue_events_url"`
				EventsUrl           string      `json:"events_url"`
				AssigneesUrl        string      `json:"assignees_url"`
				BranchesUrl         string      `json:"branches_url"`
				TagsUrl             string      `json:"tags_url"`
				BlobsUrl            string      `json:"blobs_url"`
				GitTagsUrl          string      `json:"git_tags_url"`
				GitRefsUrl          string      `json:"git_refs_url"`
				TreesUrl            string      `json:"trees_url"`
				StatusesUrl         string      `json:"statuses_url"`
				LanguagesUrl        string      `json:"languages_url"`
				StargazersUrl       string      `json:"stargazers_url"`
				ContributorsUrl     string      `json:"contributors_url"`
				SubscribersUrl      string      `json:"subscribers_url"`
				SubscriptionUrl     string      `json:"subscription_url"`
				CommitsUrl          string      `json:"commits_url"`
				GitCommitsUrl       string      `json:"git_commits_url"`
				CommentsUrl         string      `json:"comments_url"`
				IssueCommentUrl     string      `json:"issue_comment_url"`
				ContentsUrl         string      `json:"contents_url"`
				CompareUrl          string      `json:"compare_url"`
				MergesUrl           string      `json:"merges_url"`
				ArchiveUrl          string      `json:"archive_url"`
				DownloadsUrl        string      `json:"downloads_url"`
				IssuesUrl           string      `json:"issues_url"`
				PullsUrl            string      `json:"pulls_url"`
				MilestonesUrl       string      `json:"milestones_url"`
				NotificationsUrl    string      `json:"notifications_url"`
				LabelsUrl           string      `json:"labels_url"`
				ReleasesUrl         string      `json:"releases_url"`
				DeploymentsUrl      string      `json:"deployments_url"`
				CreatedAt           time.Time   `json:"created_at"`
				UpdatedAt           time.Time   `json:"updated_at"`
				PushedAt            time.Time   `json:"pushed_at"`
				GitUrl              string      `json:"git_url"`
				SshUrl              string      `json:"ssh_url"`
				CloneUrl            string      `json:"clone_url"`
				SvnUrl              string      `json:"svn_url"`
				Homepage            interface{} `json:"homepage"`
				Size                int         `json:"size"`
				StargazersCount     int         `json:"stargazers_count"`
				WatchersCount       int         `json:"watchers_count"`
				Language            string      `json:"language"`
				HasIssues           bool        `json:"has_issues"`
				HasProjects         bool        `json:"has_projects"`
				HasDownloads        bool        `json:"has_downloads"`
				HasWiki             bool        `json:"has_wiki"`
				HasPages            bool        `json:"has_pages"`
				ForksCount          int         `json:"forks_count"`
				MirrorUrl           interface{} `json:"mirror_url"`
				Archived            bool        `json:"archived"`
				Disabled            bool        `json:"disabled"`
				OpenIssuesCount     int         `json:"open_issues_count"`
				License             interface{} `json:"license"`
				Forks               int         `json:"forks"`
				OpenIssues          int         `json:"open_issues"`
				Watchers            int         `json:"watchers"`
				DefaultBranch       string      `json:"default_branch"`
				AllowSquashMerge    bool        `json:"allow_squash_merge"`
				AllowMergeCommit    bool        `json:"allow_merge_commit"`
				AllowRebaseMerge    bool        `json:"allow_rebase_merge"`
				DeleteBranchOnMerge bool        `json:"delete_branch_on_merge"`
			} `json:"repo"`
		} `json:"head"`
		Base struct {
			Label string `json:"label"`
			Ref   string `json:"ref"`
			Sha   string `json:"sha"`
			User  struct {
				Login             string `json:"login"`
				Id                int    `json:"id"`
				NodeId            string `json:"node_id"`
				AvatarUrl         string `json:"avatar_url"`
				GravatarId        string `json:"gravatar_id"`
				Url               string `json:"url"`
				HtmlUrl           string `json:"html_url"`
				FollowersUrl      string `json:"followers_url"`
				FollowingUrl      string `json:"following_url"`
				GistsUrl          string `json:"gists_url"`
				StarredUrl        string `json:"starred_url"`
				SubscriptionsUrl  string `json:"subscriptions_url"`
				OrganizationsUrl  string `json:"organizations_url"`
				ReposUrl          string `json:"repos_url"`
				EventsUrl         string `json:"events_url"`
				ReceivedEventsUrl string `json:"received_events_url"`
				Type              string `json:"type"`
				SiteAdmin         bool   `json:"site_admin"`
			} `json:"user"`
			Repo struct {
				Id       int    `json:"id"`
				NodeId   string `json:"node_id"`
				Name     string `json:"name"`
				FullName string `json:"full_name"`
				Private  bool   `json:"private"`
				Owner    struct {
					Login             string `json:"login"`
					Id                int    `json:"id"`
					NodeId            string `json:"node_id"`
					AvatarUrl         string `json:"avatar_url"`
					GravatarId        string `json:"gravatar_id"`
					Url               string `json:"url"`
					HtmlUrl           string `json:"html_url"`
					FollowersUrl      string `json:"followers_url"`
					FollowingUrl      string `json:"following_url"`
					GistsUrl          string `json:"gists_url"`
					StarredUrl        string `json:"starred_url"`
					SubscriptionsUrl  string `json:"subscriptions_url"`
					OrganizationsUrl  string `json:"organizations_url"`
					ReposUrl          string `json:"repos_url"`
					EventsUrl         string `json:"events_url"`
					ReceivedEventsUrl string `json:"received_events_url"`
					Type              string `json:"type"`
					SiteAdmin         bool   `json:"site_admin"`
				} `json:"owner"`
				HtmlUrl             string      `json:"html_url"`
				Description         string      `json:"description"`
				Fork                bool        `json:"fork"`
				Url                 string      `json:"url"`
				ForksUrl            string      `json:"forks_url"`
				KeysUrl             string      `json:"keys_url"`
				CollaboratorsUrl    string      `json:"collaborators_url"`
				TeamsUrl            string      `json:"teams_url"`
				HooksUrl            string      `json:"hooks_url"`
				IssueEventsUrl      string      `json:"issue_events_url"`
				EventsUrl           string      `json:"events_url"`
				AssigneesUrl        string      `json:"assignees_url"`
				BranchesUrl         string      `json:"branches_url"`
				TagsUrl             string      `json:"tags_url"`
				BlobsUrl            string      `json:"blobs_url"`
				GitTagsUrl          string      `json:"git_tags_url"`
				GitRefsUrl          string      `json:"git_refs_url"`
				TreesUrl            string      `json:"trees_url"`
				StatusesUrl         string      `json:"statuses_url"`
				LanguagesUrl        string      `json:"languages_url"`
				StargazersUrl       string      `json:"stargazers_url"`
				ContributorsUrl     string      `json:"contributors_url"`
				SubscribersUrl      string      `json:"subscribers_url"`
				SubscriptionUrl     string      `json:"subscription_url"`
				CommitsUrl          string      `json:"commits_url"`
				GitCommitsUrl       string      `json:"git_commits_url"`
				CommentsUrl         string      `json:"comments_url"`
				IssueCommentUrl     string      `json:"issue_comment_url"`
				ContentsUrl         string      `json:"contents_url"`
				CompareUrl          string      `json:"compare_url"`
				MergesUrl           string      `json:"merges_url"`
				ArchiveUrl          string      `json:"archive_url"`
				DownloadsUrl        string      `json:"downloads_url"`
				IssuesUrl           string      `json:"issues_url"`
				PullsUrl            string      `json:"pulls_url"`
				MilestonesUrl       string      `json:"milestones_url"`
				NotificationsUrl    string      `json:"notifications_url"`
				LabelsUrl           string      `json:"labels_url"`
				ReleasesUrl         string      `json:"releases_url"`
				DeploymentsUrl      string      `json:"deployments_url"`
				CreatedAt           time.Time   `json:"created_at"`
				UpdatedAt           time.Time   `json:"updated_at"`
				PushedAt            time.Time   `json:"pushed_at"`
				GitUrl              string      `json:"git_url"`
				SshUrl              string      `json:"ssh_url"`
				CloneUrl            string      `json:"clone_url"`
				SvnUrl              string      `json:"svn_url"`
				Homepage            interface{} `json:"homepage"`
				Size                int         `json:"size"`
				StargazersCount     int         `json:"stargazers_count"`
				WatchersCount       int         `json:"watchers_count"`
				Language            string      `json:"language"`
				HasIssues           bool        `json:"has_issues"`
				HasProjects         bool        `json:"has_projects"`
				HasDownloads        bool        `json:"has_downloads"`
				HasWiki             bool        `json:"has_wiki"`
				HasPages            bool        `json:"has_pages"`
				ForksCount          int         `json:"forks_count"`
				MirrorUrl           interface{} `json:"mirror_url"`
				Archived            bool        `json:"archived"`
				Disabled            bool        `json:"disabled"`
				OpenIssuesCount     int         `json:"open_issues_count"`
				License             interface{} `json:"license"`
				Forks               int         `json:"forks"`
				OpenIssues          int         `json:"open_issues"`
				Watchers            int         `json:"watchers"`
				DefaultBranch       string      `json:"default_branch"`
				AllowSquashMerge    bool        `json:"allow_squash_merge"`
				AllowMergeCommit    bool        `json:"allow_merge_commit"`
				AllowRebaseMerge    bool        `json:"allow_rebase_merge"`
				DeleteBranchOnMerge bool        `json:"delete_branch_on_merge"`
			} `json:"repo"`
		} `json:"base"`
		Links struct {
			Self struct {
				Href string `json:"href"`
			} `json:"self"`
			Html struct {
				Href string `json:"href"`
			} `json:"html"`
			Issue struct {
				Href string `json:"href"`
			} `json:"issue"`
			Comments struct {
				Href string `json:"href"`
			} `json:"comments"`
			ReviewComments struct {
				Href string `json:"href"`
			} `json:"review_comments"`
			ReviewComment struct {
				Href string `json:"href"`
			} `json:"review_comment"`
			Commits struct {
				Href string `json:"href"`
			} `json:"commits"`
			Statuses struct {
				Href string `json:"href"`
			} `json:"statuses"`
		} `json:"_links"`
		AuthorAssociation   string      `json:"author_association"`
		AutoMerge           interface{} `json:"auto_merge"`
		ActiveLockReason    interface{} `json:"active_lock_reason"`
		Merged              bool        `json:"merged"`
		Mergeable           interface{} `json:"mergeable"`
		Rebaseable          interface{} `json:"rebaseable"`
		MergeableState      string      `json:"mergeable_state"`
		MergedBy            interface{} `json:"merged_by"`
		Comments            int         `json:"comments"`
		ReviewComments      int         `json:"review_comments"`
		MaintainerCanModify bool        `json:"maintainer_can_modify"`
		Commits             int         `json:"commits"`
		Additions           int         `json:"additions"`
		Deletions           int         `json:"deletions"`
		ChangedFiles        int         `json:"changed_files"`
	} `json:"pull_request"`
	Repository struct {
		Id       int    `json:"id"`
		NodeId   string `json:"node_id"`
		Name     string `json:"name"`
		FullName string `json:"full_name"`
		Private  bool   `json:"private"`
		Owner    struct {
			Login             string `json:"login"`
			Id                int    `json:"id"`
			NodeId            string `json:"node_id"`
			AvatarUrl         string `json:"avatar_url"`
			GravatarId        string `json:"gravatar_id"`
			Url               string `json:"url"`
			HtmlUrl           string `json:"html_url"`
			FollowersUrl      string `json:"followers_url"`
			FollowingUrl      string `json:"following_url"`
			GistsUrl          string `json:"gists_url"`
			StarredUrl        string `json:"starred_url"`
			SubscriptionsUrl  string `json:"subscriptions_url"`
			OrganizationsUrl  string `json:"organizations_url"`
			ReposUrl          string `json:"repos_url"`
			EventsUrl         string `json:"events_url"`
			ReceivedEventsUrl string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"owner"`
		HtmlUrl          string      `json:"html_url"`
		Description      string      `json:"description"`
		Fork             bool        `json:"fork"`
		Url              string      `json:"url"`
		ForksUrl         string      `json:"forks_url"`
		KeysUrl          string      `json:"keys_url"`
		CollaboratorsUrl string      `json:"collaborators_url"`
		TeamsUrl         string      `json:"teams_url"`
		HooksUrl         string      `json:"hooks_url"`
		IssueEventsUrl   string      `json:"issue_events_url"`
		EventsUrl        string      `json:"events_url"`
		AssigneesUrl     string      `json:"assignees_url"`
		BranchesUrl      string      `json:"branches_url"`
		TagsUrl          string      `json:"tags_url"`
		BlobsUrl         string      `json:"blobs_url"`
		GitTagsUrl       string      `json:"git_tags_url"`
		GitRefsUrl       string      `json:"git_refs_url"`
		TreesUrl         string      `json:"trees_url"`
		StatusesUrl      string      `json:"statuses_url"`
		LanguagesUrl     string      `json:"languages_url"`
		StargazersUrl    string      `json:"stargazers_url"`
		ContributorsUrl  string      `json:"contributors_url"`
		SubscribersUrl   string      `json:"subscribers_url"`
		SubscriptionUrl  string      `json:"subscription_url"`
		CommitsUrl       string      `json:"commits_url"`
		GitCommitsUrl    string      `json:"git_commits_url"`
		CommentsUrl      string      `json:"comments_url"`
		IssueCommentUrl  string      `json:"issue_comment_url"`
		ContentsUrl      string      `json:"contents_url"`
		CompareUrl       string      `json:"compare_url"`
		MergesUrl        string      `json:"merges_url"`
		ArchiveUrl       string      `json:"archive_url"`
		DownloadsUrl     string      `json:"downloads_url"`
		IssuesUrl        string      `json:"issues_url"`
		PullsUrl         string      `json:"pulls_url"`
		MilestonesUrl    string      `json:"milestones_url"`
		NotificationsUrl string      `json:"notifications_url"`
		LabelsUrl        string      `json:"labels_url"`
		ReleasesUrl      string      `json:"releases_url"`
		DeploymentsUrl   string      `json:"deployments_url"`
		CreatedAt        time.Time   `json:"created_at"`
		UpdatedAt        time.Time   `json:"updated_at"`
		PushedAt         time.Time   `json:"pushed_at"`
		GitUrl           string      `json:"git_url"`
		SshUrl           string      `json:"ssh_url"`
		CloneUrl         string      `json:"clone_url"`
		SvnUrl           string      `json:"svn_url"`
		Homepage         interface{} `json:"homepage"`
		Size             int         `json:"size"`
		StargazersCount  int         `json:"stargazers_count"`
		WatchersCount    int         `json:"watchers_count"`
		Language         string      `json:"language"`
		HasIssues        bool        `json:"has_issues"`
		HasProjects      bool        `json:"has_projects"`
		HasDownloads     bool        `json:"has_downloads"`
		HasWiki          bool        `json:"has_wiki"`
		HasPages         bool        `json:"has_pages"`
		ForksCount       int         `json:"forks_count"`
		MirrorUrl        interface{} `json:"mirror_url"`
		Archived         bool        `json:"archived"`
		Disabled         bool        `json:"disabled"`
		OpenIssuesCount  int         `json:"open_issues_count"`
		License          interface{} `json:"license"`
		Forks            int         `json:"forks"`
		OpenIssues       int         `json:"open_issues"`
		Watchers         int         `json:"watchers"`
		DefaultBranch    string      `json:"default_branch"`
	} `json:"repository"`
	Sender struct {
		Login             string `json:"login"`
		Id                int    `json:"id"`
		NodeId            string `json:"node_id"`
		AvatarUrl         string `json:"avatar_url"`
		GravatarId        string `json:"gravatar_id"`
		Url               string `json:"url"`
		HtmlUrl           string `json:"html_url"`
		FollowersUrl      string `json:"followers_url"`
		FollowingUrl      string `json:"following_url"`
		GistsUrl          string `json:"gists_url"`
		StarredUrl        string `json:"starred_url"`
		SubscriptionsUrl  string `json:"subscriptions_url"`
		OrganizationsUrl  string `json:"organizations_url"`
		ReposUrl          string `json:"repos_url"`
		EventsUrl         string `json:"events_url"`
		ReceivedEventsUrl string `json:"received_events_url"`
		Type              string `json:"type"`
		SiteAdmin         bool   `json:"site_admin"`
	} `json:"sender"`
}

// github push 执行 CI 所需字段
type HandleGithubPushJson struct {
	Repository struct {
		FullName  string    `json:"full_name"`
		UpdatedAt time.Time `json:"updated_at"`
		GitUrl    string    `json:"git_url"`
		SshUrl    string    `json:"ssh_url"`
		CloneUrl  string    `json:"clone_url"` // cloneurl就是htpps
	} `json:"repository"`
}

// github pr 执行 CI 所需字段
type HandleGithubPRJson struct {
	Action     string `json:"action"`
	Repository struct {
		FullName  string    `json:"full_name"`
		UpdatedAt time.Time `json:"updated_at"`
		GitUrl    string    `json:"git_url"`
		SshUrl    string    `json:"ssh_url"`
		CloneUrl  string    `json:"clone_url"`
	} `json:"repository"`
}
