// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/api/casbinList": {
            "get": {
                "description": "获取用户已有的API权限列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Api相关"
                ],
                "summary": "获取用户已有的API权限列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 登录返回的用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "description": "组ID",
                        "name": "gid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/api/delApi": {
            "delete": {
                "description": "删除API",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Api相关"
                ],
                "summary": "删除API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 登录返回的用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "id",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.IdsReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/api/fresh": {
            "get": {
                "description": "刷新casbin缓存",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Api相关"
                ],
                "summary": "刷新casbin缓存",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 登录返回的用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/api/getApiList": {
            "post": {
                "description": "获取Api列表 可分页",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Api相关"
                ],
                "summary": "获取Api列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 登录返回的用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "每页大小",
                        "name": "page_size",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/api/updateApi": {
            "post": {
                "description": "新增或者修改Api",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Api相关"
                ],
                "summary": "新增或者修改Api",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 登录返回的用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "api组",
                        "name": "apiGroup",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "api中文描述",
                        "name": "description",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "修改才需要传，没有传算新增",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "方法:创建/更新POST(默认)|查看GET|删除DELETE",
                        "name": "method",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "api路径",
                        "name": "path",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/api/updateCasbin": {
            "post": {
                "description": "为用户分配API权限",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Api相关"
                ],
                "summary": "为用户分配API权限",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 登录返回的用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "为用户分配API权限的请求",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CasbinInReceiveReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/group/association": {
            "put": {
                "description": "关联用户，关联成功data返回组和关联用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户组相关"
                ],
                "summary": "关联用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "输入组ID和对应用户IDs",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UpdateUserAssReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/group/delete": {
            "delete": {
                "description": "删除成功返回sucess",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户组相关"
                ],
                "summary": "删除用户组",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "要删除的组ID",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.IdsReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/group/getGroups": {
            "get": {
                "description": "返回指定用户组/不传Name返回所有用户组",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户组相关"
                ],
                "summary": "获取用户组",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页大小",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/group/getProjectAss": {
            "get": {
                "description": "返回组关联的项目",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户组相关"
                ],
                "summary": "获取组关联项目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页大小",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/group/getUserAss": {
            "get": {
                "description": "返回组关联的用户",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户组相关"
                ],
                "summary": "获取组关联用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页大小",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/group/update": {
            "post": {
                "description": "新增不用传ID，修改才传ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户组相关"
                ],
                "summary": "新增/修改用户组信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "修改才需要传，没有传算新增",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "mark",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "工作室不用传，项目组传工作室的ID",
                        "name": "parent_id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/host/Host": {
            "get": {
                "description": "全部查询不传Ip",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务器相关"
                ],
                "summary": "查询服务器",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "查询IP则输入IP，v4或v6都可以",
                        "name": "ip",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/host/Project": {
            "get": {
                "description": "返回项目切片",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务器相关"
                ],
                "summary": "查询服务器对应项目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页大小",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/host/assDomain": {
            "put": {
                "description": "服务器ID[多选]",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务器相关"
                ],
                "summary": "域名关联服务器",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "关联传入参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UpdateDomainAssHostReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/host/association": {
            "put": {
                "description": "项目ID[多选]",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务器相关"
                ],
                "summary": "关联项目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "关联传入参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UpdateHostAssProjectReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/host/domainAssHost": {
            "get": {
                "description": "返回服务器切片",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务器相关"
                ],
                "summary": "查询域名对应服务器",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页大小",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/host/update": {
            "post": {
                "description": "返回新增/修改的指定服务器",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务器相关"
                ],
                "summary": "新增/修改服务器",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "1 按量收费, 2 包月收费, 3 包年收费 ...后续有需要再加",
                        "name": "billing",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "cloud",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "四核输入4",
                        "name": "cores",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "磁盘单位为G",
                        "name": "data_disk",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "name": "iops",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "ipv4",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "ipv6",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "name": "mbps",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "内存单位为G",
                        "name": "mem",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "name": "password",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "port",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "system",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "磁盘单位为G",
                        "name": "system_disk",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "1 单服机器, 2 中央服机器, 3 CDN机器, 4 业务服机器  ...后续有需要再加",
                        "name": "type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "user",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "所在地",
                        "name": "zone",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "时区，如东八区填8",
                        "name": "zone_time",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/host/updateDomain": {
            "post": {
                "description": "返回新增或修改的指定域名",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务器相关"
                ],
                "summary": "新增/修改域名",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "domain",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/login": {
            "post": {
                "description": "用户名长度不少于3位，密码不少于6位",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "maxLength": 20,
                        "minLength": 8,
                        "type": "string",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "maxLength": 30,
                        "minLength": 5,
                        "type": "string",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{\"status\":200\",msg\":\"登录成功\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "400": {
                        "description": "{\"data\":{}, \"meta\":{\"status\":400,\"msg\":\"错误信息\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/association": {
            "put": {
                "description": "关联用户组，关联成功data返回组和关联用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单相关"
                ],
                "summary": "关联用户组",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "输入菜单ID和对应用户组IDs",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UpdateMenuAssReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/delete": {
            "delete": {
                "description": "删除成功返回success",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单相关"
                ],
                "summary": "删除菜单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "菜单ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.IdsReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/getMenus": {
            "get": {
                "description": "返回关联的菜单",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单相关"
                ],
                "summary": "获取用户组对应菜单信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/update": {
            "post": {
                "description": "新增不用传ID，修改才传ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单相关"
                ],
                "summary": "新增/修改菜单信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "创建人",
                        "name": "author",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "组件",
                        "name": "component",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "菜单图标",
                        "name": "icon",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "修改才需要传，没有传算新增",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "前端标志",
                        "name": "mark",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "对应主菜单的ID",
                        "name": "parent_id",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "排序标记",
                        "name": "sort",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "前端展示菜单名",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "前端类型",
                        "name": "type",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "前端路由",
                        "name": "url",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/ping": {
            "get": {
                "description": "无设置权限，返回\"Hello world!~~(无权限版)\"",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "测试相关"
                ],
                "summary": "测试Gin能否正常访问",
                "responses": {
                    "200": {
                        "description": "{\"message\": \"Hello world!~~(无权限版)\"}",
                        "schema": {
                            "type": ""
                        }
                    }
                }
            }
        },
        "/api/v1/ping2": {
            "get": {
                "description": "有设置权限，返回\"Hello world!~~(有权限版)\"",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "测试相关"
                ],
                "summary": "测试Gin通过认证能否正常访问",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 登录返回的用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\": \"Hello world!~~(有权限版)\"}",
                        "schema": {
                            "type": ""
                        }
                    }
                }
            }
        },
        "/api/v1/project/association": {
            "put": {
                "description": "服务器ID[多选]",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目相关"
                ],
                "summary": "关联服务器",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "关联传入参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UpdateProjectAssHostReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/project/getHost": {
            "get": {
                "description": "返回服务器切片",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目相关"
                ],
                "summary": "获取项目对应的服务器",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页大小",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/project/getProject": {
            "get": {
                "description": "返回指定项目",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目相关"
                ],
                "summary": "获取项目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页大小",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/project/getSelfProject": {
            "get": {
                "description": "返回自身所属项目",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目相关"
                ],
                "summary": "获取自身所属项目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "每页大小",
                        "name": "page_size",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/project/update": {
            "post": {
                "description": "返回success",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目相关"
                ],
                "summary": "删除项目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "删除project所需参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.IdsReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/ssh/testSSH": {
            "post": {
                "description": "传入SSH命令所需参数",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SSH相关"
                ],
                "summary": "测试SSH命令执行",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "传入所需id",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.TestSSHReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/task/association": {
            "put": {
                "description": "服务器ID[多选]",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务相关"
                ],
                "summary": "关联服务器",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "关联传入参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UpdateTemplateAssHostReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/task/conditionSet": {
            "get": {
                "description": "可不选或多选,有需要再让运维从代码中添加功能",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务相关"
                ],
                "summary": "获取可输入条件集合",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/task/deleteTemplate": {
            "delete": {
                "description": "删除的任务模板",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务相关"
                ],
                "summary": "删除任务模板",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "所需参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.IdsReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/task/getTemplate": {
            "get": {
                "description": "传ID(Task)返回模板内容/只传项目ID返回包含任务类型/传任务类型和项目ID返回包含模板名",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务相关"
                ],
                "summary": "获取任务模板",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "传Task的ID查询，则无需填其它参数，返回Task的所有内容",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页大小",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "传Pid不传typename，返回对应Type的Name及其ID和 及Type包含的Task的Name和ID",
                        "name": "pid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "需要精确到类型, 则传项目ID和类型名",
                        "name": "type_name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/task/template": {
            "post": {
                "description": "运营点击发出工单/运维审批最后确认 都可以修改",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务相关"
                ],
                "summary": "新增/修改任务模板",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "更新taskTem所需参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UpdateTaskTemplateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{返回新增/修改的项目任务模板},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/delete": {
            "delete": {
                "description": "删除用户",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户IDs",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.IdsReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/getActLog": {
            "get": {
                "description": "获取用户操作记录，不包含get",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "获取用户操作记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页大小",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "username",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{用户记录},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/getAssGroup": {
            "get": {
                "description": "返回用户关联的组",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "获取关联组",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/getSelfAssGroup": {
            "get": {
                "description": "返回用户本身关联的组",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "获取用户本身关联的组",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/getSelfInfo": {
            "get": {
                "description": "获取用户个人信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "用户个人信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/keyFile": {
            "post": {
                "description": "是私钥不要提交公钥！私钥如: id_rsa",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "提交自身私钥文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "私钥文件上传",
                        "name": "keyFile",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "私钥通行证密码上传",
                        "name": "KeyPasswd",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{用户记录},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/keyStr": {
            "post": {
                "description": "是私钥字符串不要提交公钥文件！私钥如: id_rsa的内容",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "提交自身私钥字符串",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "私钥文本内容上传",
                        "name": "keyStr",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "私钥通行证密码上传",
                        "name": "KeyPasswd",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{用户记录},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/logout": {
            "put": {
                "description": "登出 - 把JWT拉入黑名单",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "登出",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{\"status\":200\",msg\":\"登出成功\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "400": {
                        "description": "{\"data\":{}, \"meta\":{\"status\":400,\"msg\":\"错误信息\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/password": {
            "patch": {
                "description": "修改用户密码",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "修改用户密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "maxLength": 20,
                        "minLength": 8,
                        "type": "string",
                        "description": "要求密码长度不小于8不大于20",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/search": {
            "get": {
                "description": "获取用户列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "获取用户列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "每页大小",
                        "name": "page_size",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "用户名称(可选)",
                        "name": "username",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\",\"Data\":\"User信息\",\"Page\":\"页码\",\"PageSize\":\"单页条数\",\"Total\":\"总条数\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/selfPassword": {
            "patch": {
                "description": "修改用户自己的密码",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "修改用户自己的密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "需要修改的密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/status": {
            "patch": {
                "description": "status参数：恢复用户传1，禁用用户传2",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "修改用户状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "status",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/update": {
            "post": {
                "description": "新增不用传用户ID，修改才传用户ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "新增/修改用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "expiration",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "修改才需要传，没有传算新增",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "管理员传1，不然不用传",
                        "name": "is_admin",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "mobile",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "maxLength": 30,
                        "minLength": 5,
                        "type": "string",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.CasbinInReceiveReq": {
            "type": "object",
            "required": [
                "group_id"
            ],
            "properties": {
                "group_id": {
                    "description": "组id",
                    "type": "string"
                },
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "api.IdsReq": {
            "type": "object",
            "required": [
                "ids"
            ],
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "api.PageInfo": {
            "type": "object",
            "properties": {
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页大小",
                    "type": "integer"
                }
            }
        },
        "api.TestSSHReq": {
            "type": "object",
            "properties": {
                "host_id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "api.UpdateDomainAssHostReq": {
            "type": "object",
            "required": [
                "did"
            ],
            "properties": {
                "did": {
                    "type": "integer"
                },
                "hids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "api.UpdateHostAssProjectReq": {
            "type": "object",
            "required": [
                "hid"
            ],
            "properties": {
                "hid": {
                    "type": "integer"
                },
                "pid": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "api.UpdateMenuAssReq": {
            "type": "object",
            "required": [
                "group_id",
                "menu_id"
            ],
            "properties": {
                "group_id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "menu_id": {
                    "type": "integer"
                }
            }
        },
        "api.UpdateProjectAssHostReq": {
            "type": "object",
            "required": [
                "hid"
            ],
            "properties": {
                "hid": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "pid": {
                    "type": "integer"
                }
            }
        },
        "api.UpdateTaskTemplateReq": {
            "type": "object",
            "required": [
                "condition",
                "pid",
                "task",
                "task_name",
                "type_name"
            ],
            "properties": {
                "args": {
                    "description": "任意变量, 如: path=/data/a_b_c",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "comment": {
                    "description": "模板备注",
                    "type": "string"
                },
                "condition": {
                    "description": "mem=5就是单服最少5G，还有iowait/idle/load",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "description": "修改才需要传，没有传算新增",
                    "type": "integer"
                },
                "pid": {
                    "description": "对应项目ID",
                    "type": "integer"
                },
                "port_rule": {
                    "description": "端口规则, 如: 10000 + flag % 1000",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "task": {
                    "description": "任务内容，规定用Shell",
                    "type": "string"
                },
                "task_name": {
                    "description": "模板名",
                    "type": "string"
                },
                "type_name": {
                    "description": "模板类型名",
                    "type": "string"
                }
            }
        },
        "api.UpdateTemplateAssHostReq": {
            "type": "object",
            "required": [
                "hid"
            ],
            "properties": {
                "hid": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "tid": {
                    "type": "integer"
                }
            }
        },
        "api.UpdateUserAssReq": {
            "type": "object",
            "required": [
                "group_id",
                "user_id"
            ],
            "properties": {
                "group_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
