// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/api/delApi": {
            "delete": {
                "description": "删除API",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Api相关"
                ],
                "summary": "删除API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 登录返回的用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "name": "ids",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/api/fresh": {
            "get": {
                "description": "刷新casbin缓存",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Api相关"
                ],
                "summary": "刷新casbin缓存",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 登录返回的用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/api/getApiList": {
            "post": {
                "description": "获取Api列表 可分页",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Api相关"
                ],
                "summary": "获取Api列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 登录返回的用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "每页大小",
                        "name": "page_size",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/api/getCasbinList": {
            "get": {
                "description": "获取用户已有的API权限列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Api相关"
                ],
                "summary": "获取用户已有的API权限列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 登录返回的用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "组ID",
                        "name": "gid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/api/updateApi": {
            "post": {
                "description": "新增或者修改Api",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Api相关"
                ],
                "summary": "新增或者修改Api",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 登录返回的用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "api组",
                        "name": "apiGroup",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "api中文描述",
                        "name": "description",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "修改才需要传，没有传算新增",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "方法:创建/更新POST(默认)|查看GET|删除DELETE",
                        "name": "method",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "api路径",
                        "name": "path",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/api/updateCasbin": {
            "post": {
                "description": "为用户分配API权限",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Api相关"
                ],
                "summary": "为用户分配API权限",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 登录返回的用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "为用户分配API权限的请求",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CasbinInReceiveReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/group/association": {
            "put": {
                "description": "关联用户，关联成功data返回组和关联用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户组相关"
                ],
                "summary": "关联用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "输入组ID和对应用户IDs",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UpdateUserAssReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/group/getGroups": {
            "get": {
                "description": "返回指定用户组/不传Name返回所有用户组",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户组相关"
                ],
                "summary": "获取用户组",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "输入组名，不输入则全部返回",
                        "name": "id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.GetGroupReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/group/getProjectAss": {
            "post": {
                "description": "返回组关联的项目",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户组相关"
                ],
                "summary": "获取组关联项目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "传参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.GetGroupAssIdReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/group/getUserAss": {
            "post": {
                "description": "返回组关联的用户",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户组相关"
                ],
                "summary": "获取组关联用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "传参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.GetGroupAssIdReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/group/update": {
            "post": {
                "description": "新增不用传ID，修改才传ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户组相关"
                ],
                "summary": "新增/修改用户组信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "修改才需要传，没有传算新增",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "mark",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "工作室不用传，项目组传工作室的ID",
                        "name": "parent_id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/host/association": {
            "put": {
                "description": "项目ID[多选]",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务器相关"
                ],
                "summary": "关联项目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "关联传入参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UpdateHostAssProjectReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/host/delete": {
            "delete": {
                "description": "传服务器ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务器相关"
                ],
                "summary": "删除服务器",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "需删除的host ID",
                        "name": "id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/host/getHost": {
            "post": {
                "description": "全部查询不传Ip",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务器相关"
                ],
                "summary": "查询服务器",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "获取host的参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.GetHostReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/host/getProject": {
            "get": {
                "description": "返回项目切片",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务器相关"
                ],
                "summary": "查询服务器对应项目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "传参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.GetHostAssProject"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/host/update": {
            "post": {
                "description": "返回新增/修改的指定服务器",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务器相关"
                ],
                "summary": "新增/修改服务器",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "1 按量收费, 2 包月收费, 3 包年收费 ...后续有需要再加",
                        "name": "billing",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "cloud",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "四核输入4",
                        "name": "cores",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "磁盘单位为G",
                        "name": "data_disk",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "name": "iops",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "ipv4",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "ipv6",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "name": "mbps",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "内存单位为G",
                        "name": "mem",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "system",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "磁盘单位为G",
                        "name": "system_disk",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "1 单服机器, 2 中央服机器, 3 CDN机器, 4 业务服机器  ...后续有需要再加",
                        "name": "type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "所在地",
                        "name": "zone",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "时区，如东八区填8",
                        "name": "zone_time",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/login": {
            "post": {
                "description": "用户名长度不少于3位，密码不少于6位",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "maxLength": 20,
                        "minLength": 8,
                        "type": "string",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "maxLength": 30,
                        "minLength": 5,
                        "type": "string",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{\"status\":200\",msg\":\"登录成功\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "400": {
                        "description": "{\"data\":{}, \"meta\":{\"status\":400,\"msg\":\"错误信息\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/association": {
            "put": {
                "description": "关联用户组，关联成功data返回组和关联用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单相关"
                ],
                "summary": "关联用户组",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "输入菜单ID和对应用户组IDs",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UpdateMenuAssReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/getMenus": {
            "get": {
                "description": "返回指定菜单和关联的用户组切片",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单相关"
                ],
                "summary": "获取菜单及对应用户组信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "输入菜单ID，获取菜单和关联用户组,不输入返回所有菜单及关联用户组",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/update": {
            "post": {
                "description": "新增不用传ID，修改才传ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单相关"
                ],
                "summary": "新增/修改菜单信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "创建人",
                        "name": "author",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "组件",
                        "name": "component",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "菜单图标",
                        "name": "icon",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "修改才需要传，没有传算新增",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "前端标志",
                        "name": "mark",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "对应主菜单的ID",
                        "name": "parent_id",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "排序标记",
                        "name": "sort",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "前端展示菜单名",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "前端类型",
                        "name": "type",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "前端路由",
                        "name": "url",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/ping": {
            "get": {
                "description": "无设置权限，返回\"Hello world!~~(无权限版)\"",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "测试相关"
                ],
                "summary": "测试Gin能否正常访问",
                "responses": {
                    "200": {
                        "description": "{\"message\": \"Hello world!~~(无权限版)\"}",
                        "schema": {
                            "type": ""
                        }
                    }
                }
            }
        },
        "/api/v1/ping2": {
            "get": {
                "description": "有设置权限，返回\"Hello world!~~(有权限版)\"",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "测试相关"
                ],
                "summary": "测试Gin通过认证能否正常访问",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 登录返回的用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\": \"Hello world!~~(有权限版)\"}",
                        "schema": {
                            "type": ""
                        }
                    }
                }
            }
        },
        "/api/v1/project/association": {
            "put": {
                "description": "服务器ID[多选]",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目相关"
                ],
                "summary": "关联服务器",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "关联传入参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UpdateProjectAssHostReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/project/getHost": {
            "post": {
                "description": "返回服务器切片",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目相关"
                ],
                "summary": "获取项目对应的服务器",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "获取关联host的参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.GetHostAssReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/project/getProject": {
            "post": {
                "description": "返回指定项目",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目相关"
                ],
                "summary": "获取项目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "输入项目ID，获取项目,不输入返回所有项目",
                        "name": "data",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/api.GetProjectReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/project/getSelfProject": {
            "get": {
                "description": "返回自身所属项目",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目相关"
                ],
                "summary": "获取自身所属项目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/project/update": {
            "post": {
                "description": "返回新增/修改的指定项目",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目相关"
                ],
                "summary": "新增/修改项目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "group_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "修改才需要传，没有传算新增",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "status",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/actLog": {
            "post": {
                "description": "获取用户操作记录，不包含get",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "获取用户操作记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户username",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.GetRecordReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{用户记录},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/delete": {
            "delete": {
                "description": "删除用户",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户IDs",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.IdsReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/getAssGroup": {
            "get": {
                "description": "返回用户关联的组",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "获取关联组",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "用户的ID",
                        "name": "uid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/getSelfAssGroup": {
            "get": {
                "description": "返回用户本身关联的组",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "获取用户本身关联的组",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/getSelfInfo": {
            "get": {
                "description": "获取用户个人信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "用户个人信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/keyFile": {
            "post": {
                "description": "是私钥不要提交公钥！私钥如: id_rsa",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "提交自身私钥文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "私钥文件上传",
                        "name": "keyFile",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{用户记录},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/keyStr": {
            "post": {
                "description": "是私钥字符串不要提交公钥文件！私钥如: id_rsa的内容",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "提交自身私钥字符串",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "私钥文本内容上传",
                        "name": "keyStr",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{用户记录},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/logout": {
            "put": {
                "description": "登出 - 把JWT拉入黑名单",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "登出",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{\"status\":200\",msg\":\"登出成功\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "400": {
                        "description": "{\"data\":{}, \"meta\":{\"status\":400,\"msg\":\"错误信息\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/password": {
            "patch": {
                "description": "修改用户密码",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "修改用户密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "maxLength": 20,
                        "minLength": 8,
                        "type": "string",
                        "description": "要求密码长度不小于8不大于20",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/search": {
            "post": {
                "description": "获取用户列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "获取用户列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "每页大小",
                        "name": "page_size",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "用户名称(可选)",
                        "name": "username",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\",\"Data\":\"User信息\",\"Page\":\"页码\",\"PageSize\":\"单页条数\",\"Total\":\"总条数\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/selfPassword": {
            "patch": {
                "description": "修改用户自己的密码",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "修改用户自己的密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "需要修改的密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/status": {
            "patch": {
                "description": "status参数：恢复用户传1，禁用用户传2",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "修改用户状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "status",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/update": {
            "post": {
                "description": "新增不用传用户ID，修改才传用户ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "新增/修改用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "格式为：Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "expiration",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "修改才需要传，没有传算新增",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "管理员传1，不然不用传",
                        "name": "is_admin",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "mobile",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "maxLength": 30,
                        "minLength": 5,
                        "type": "string",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\":{},\"meta\":{msg\":\"Success\"}}",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "{\"data\":{}, \"meta\":{\"msg\":\"错误信息\", \"error\":\"错误格式输出(如存在)\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.CasbinInReceiveReq": {
            "type": "object",
            "required": [
                "group_id"
            ],
            "properties": {
                "group_id": {
                    "description": "组id",
                    "type": "string"
                },
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "api.GetGroupAssIdReq": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页大小",
                    "type": "integer"
                }
            }
        },
        "api.GetGroupReq": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页大小",
                    "type": "integer"
                }
            }
        },
        "api.GetHostAssProject": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页大小",
                    "type": "integer"
                }
            }
        },
        "api.GetHostAssReq": {
            "type": "object",
            "required": [
                "project_id"
            ],
            "properties": {
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页大小",
                    "type": "integer"
                },
                "project_id": {
                    "type": "integer"
                }
            }
        },
        "api.GetHostReq": {
            "type": "object",
            "properties": {
                "ip": {
                    "description": "查询IP则输入IP，v4或v6都可以",
                    "type": "string"
                },
                "page_info": {
                    "$ref": "#/definitions/api.PageInfo"
                }
            }
        },
        "api.GetProjectReq": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页大小",
                    "type": "integer"
                }
            }
        },
        "api.GetRecordReq": {
            "type": "object",
            "properties": {
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页大小",
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "api.IdsReq": {
            "type": "object",
            "required": [
                "ids"
            ],
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "api.PageInfo": {
            "type": "object",
            "properties": {
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页大小",
                    "type": "integer"
                }
            }
        },
        "api.UpdateHostAssProjectReq": {
            "type": "object",
            "required": [
                "hid"
            ],
            "properties": {
                "hid": {
                    "type": "integer"
                },
                "pid": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "api.UpdateMenuAssReq": {
            "type": "object",
            "required": [
                "group_id",
                "menu_id"
            ],
            "properties": {
                "group_id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "menu_id": {
                    "type": "integer"
                }
            }
        },
        "api.UpdateProjectAssHostReq": {
            "type": "object",
            "required": [
                "hid"
            ],
            "properties": {
                "hid": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "pid": {
                    "type": "integer"
                }
            }
        },
        "api.UpdateUserAssReq": {
            "type": "object",
            "required": [
                "group_id",
                "user_id"
            ],
            "properties": {
                "group_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
