mysql:
  conf: "root:fqh123456@tcp(192.168.18.65:20001)/fqhWeb?charset=utf8&parseTime=True&loc=Local"
  # 设置Mysql的批处理大小
  createBatchSize: 1000
  # 表前缀
  tablePrefix: "fqh_"

logger:
  level: "Debug"

sshTimeout:
  # 仅限整数，1h就是1小时，1m就是一分钟等,最大只能是h
  # 默认1h
  sshTimeout: 1h

# 允许多少个任务同时执行，设置为0则无并发上限
concurrency:
  number: 5000

# webhook的secret
gitWebhook:
  githubSecret: "fanqihang"
  gitlabSecret: "fanqihang"
  # 只是临时测试一下，一般情况下可以用/data/git_ci_script和/data/git_ci_repo
  gitCiScriptDir: "/tmp"
  gitCiRepo: "/tmp"

system:
  # mode: "product"
  mode: "develop"

securityVars:
  # AES的KEY与IV
  aesKey: "0388f9c2cd9e83960fe64589"
  aesIv: "b0bddbefd6ac81ca"
  # tokentime  仅限整数，1h就是1小时，1m就是一分钟等,最大只能是h
  tokenExpireDuration: "168h"
  # token key
  tokenKey: "52995df076de0cf040055a9e932687209c148e75cc283f5a22c341a84e4e33dc"
  # Client Ci md5 Key
  ciMd5Key: "5a9042bc95e4d56d940"
